name: auto-pull-request

# All branches except for main.
on:
  push:
    branches:
      - '**'
      - '!main'

env:
  FAKE_ENV: "fake_env123"
  FAKE_ENV2: "fake_env999"

jobs:
  launch_beta:
    uses: nellogan/CICDTest/.github/workflows/beta.yml@main
    with:
      my_site: 'mysite.com'
      passed_env: "123"
      passed_env2: "999"
#      passed_env2: "$FAKE_ENV2"