name: auto-pull-request

# All branches except for main.
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  launch_beta:
    uses: nellogan/CICDTest/.github/workflows/beta.yml@main
    with:
      my_site: 'mysite.com'