name: auto-pull-request

# All branches except for main.
on:
  push:
    branches:
      - '**'
      - '!main'
    workflow_call:
      inputs:
        PR_NUMBER:
          required: true
          type: string

# Automatically open a pull request when a trusted member pushes.
# Todo only supports owner update to check for trusted members instead.
jobs:
  open-or-update-pull-request:
    # If using a team based structure instead of a solo developer.
    # if: ${{ github.actor == github.team_slug && github.actor.permissions == approved }}

    if: ${{ github.actor == github.repository_owner }}

    runs-on: ubuntu-latest
    steps:
      - name: 'Create pull request'
        uses: actions/github-script@v7
        with:
#          github-token: ${{ secrets.CICD_REAL2 }}
          script: |
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: context.ref,
              base: 'main',
              state: 'open',
            });
            
            let pr_object;
            let pr_number = 0;
            
            if (pulls.data.length < 1) {
              pr_object = await github.rest.pulls.create({
                title: 'Automatically generated pull request.',
                owner: owner,
                repo: repo,
                head: context.ref,
                base: 'main',
                body: [
                  'A team member made a push to a feature branch which automatically generated pull request.',
                  'Author: ${{ github.actor }}',
                  'Commit message: ${{ github.event.head_commit.message }}',
                ].join('\n'),
              });
              pr_number = pr_object.data.number;
            } else {
              const existingPR = pulls.data[0];
              pr_object = await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: existingPR.number,
                body: [
                  `Updated by Job ${ context.job }`, 
                  'Author: ${{ github.actor }}',
                  'Commit message: ${{ github.event.head_commit.message }}',
                ].join('\n'),
              });
              pr_number = existingPR.number;
            }
            console.log("pr_number: ", pr_number);
            
            process.env.PR_NUMBER = pr_number;
            console.log("process.env.PR_NUMBER: ", process.env.PR_NUMBER);

#            const env_pr_number = process.env.PR_NUMBER;
#            console.log("checking pr_number: ", pr_number);


  trigger-build-test-deploy-workflow-run:
    uses: nellogan/CICDTest/.github/workflows/build-test-deploy-workflow.yml@main
    with:
      PR_NUMBER: 338
#          PR_NUMBER: ${{ process.env.PR_NUMBER }}