name: auto-pull-request

on:
  push

permissions: write-all

env:
#  GITHUB_TOKEN: ${{ secrets.CICDTEST }}
  GITHUB_TOKEN: ${{ secrets.CICDWTF }}

# Automatically open a pull request when a trusted member pushes.
# Todo only supports owner update to check for trusted members instead.
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
#    if: ${{ github.actor == github.repository_owner }}
    permissions:
      pull-requests: write
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false
#
#      - name: 'Close pull request'
#        uses: actions/github-script@v6
#        with:
#          script: |
#            console.log("check\n");
#            const { repo, owner } = context.repo;
#            const pulls2 = await github.rest.pulls.list({
#              owner: owner,
#              repo: repo,
#              head: context.ref,
#              base: 'main',
#              state: 'open',
#            });
#            const existing_pr = pulls2.data[0];
#            console.log("existing_pr", existing_pr);
#            const close_pr = await github.rest.pulls.update({
#              owner: owner,
#              repo: repo,
#              pull_number: existing_pr.number,
#              state: "closed",
#            });
#            console.log("close_pr", close_pr);
#            const reopen_pr = await github.rest.pulls.update({
#             owner: owner,
#             repo: repo,
#             pull_number: existing_pr.number,
#             state: "open",
#            });
#            console.log("reopen_pr", close_pr);