name: auto-pull-request

on:
  push

permissions: write-all

#env:
##  GITHUB_TOKEN: ${{ secrets.CICDTEST }}
#  GITHUB_TOKEN: ${{ secrets.CICDWTF }}

# Automatically open a pull request when a trusted member pushes.
# Todo only supports owner update to check for trusted members instead.
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CICDWTF }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: x-branch
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
          labels: |
            report
            automated pr
          assignees: nellogan
          reviewers: nellogan
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false


#        uses: actions/github-script@v6
#        with:
#          script: |
#            const { repo, owner } = context.repo;
#            const pulls = await github.rest.pulls.list({
#              owner: owner,
#              repo: repo,
#              head: context.ref,
#              base: 'main',
#              state: 'open',
#            });
#            if (pulls.data.length < 1) {
#              await github.rest.pulls.create({
#                title: '[CI] Merge beta into main',
#                owner: owner,
#                repo: repo,
#                head: context.ref,
#                base: 'main',
#                body: [
#                  'This PR is auto-generated by',
#                  '[actions/github-script](https://github.com/actions/github-script)',
#                ].join('\n'),
#              });
#            } else {
#              const existing_pr = pulls.data[0];
#              await github.rest.pulls.update({
#                owner: owner,
#                repo: repo,
#                pull_number: existing_pr.number,
#                body: [
#                  existing_pr.body,
#                  `Updated by Job ${context.job}`,
#                ].join('\n'),
#              });
#            }
##
##      - name: 'Close pull request'
##        uses: actions/github-script@v6
##        with:
##          script: |
##            console.log("check\n");
##            const { repo, owner } = context.repo;
##            const pulls2 = await github.rest.pulls.list({
##              owner: owner,
##              repo: repo,
##              head: context.ref,
##              base: 'main',
##              state: 'open',
##            });
##            const existing_pr = pulls2.data[0];
##            console.log("existing_pr", existing_pr);
##            const close_pr = await github.rest.pulls.update({
##              owner: owner,
##              repo: repo,
##              pull_number: existing_pr.number,
##              state: "closed",
##            });
##            console.log("close_pr", close_pr);
##            const reopen_pr = await github.rest.pulls.update({
##             owner: owner,
##             repo: repo,
##             pull_number: existing_pr.number,
##             state: "open",
##            });
##            console.log("reopen_pr", close_pr);