name: auto-pull-request

on:
  push

permissions: write-all

env:
#  GITHUB_TOKEN: ${{ secrets.CICDTEST }}
  GITHUB_TOKEN: ${{ secrets.CICDWTF }}

# Automatically open a pull request when a trusted member pushes.
# Todo only supports owner update to check for trusted members instead.
jobs:
  open-pull-request:
    runs-on: ubuntu-latest
#    if: ${{ github.actor == github.repository_owner }}
#    permissions:
#      contents: write
#      pull-requests: write
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CICDWTF }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false