name: beta

on:
  workflow_call:
    inputs:
      my_site:
        type: string
        required: true
      FAKE_ENV:
        type: string
        required: true
      FAKE_ENV2:
        type: string
        required: true



jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print data passed from workflow_caller
        run: |
          echo "my_site: ${{ inputs.my_site }}"
          echo "fake env: ${{ inputs.FAKE_ENV }}"
          echo "fake env2: ${{ inputs.FAKE_ENV2 }}"