name: beta

on:
  workflow_call:
    inputs:
      my_site:
        type: string
        required: true
      passed_env:
        type: string
        required: true
      passed_env2:
        type: string
        required: true

env:
  WTF: Monday
  PR_NUMBER: 777

jobs:
  work1:
    # If using a team based structure instead of a solo developer.
    # if: ${{ github.actor == github.team_slug && github.actor.permissions == approved }}

    if: ${{ github.actor == github.repository_owner }}

    runs-on: ubuntu-latest
    steps:
      - name: 'Create pull request'
        uses: actions/github-script@v7
        with:
#          github-token: ${{ secrets.CICD_REAL2 }}
          script: |
            const { repo, owner } = context.repo;

  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print data passed from workflow_caller
        run: |
          echo "my_site: ${{ inputs.my_site }}"
          echo "fake passed_env: $PR_NUMBER"
          echo "fake passed_env2: ${{ inputs.passed_env2 }}"