name: beta

on:
  workflow_call:
    inputs:
      my_site:
        default: 'default string'
        type: 'string'
        required: true


jobs:
  beta-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Check out this repo and submodules."
        uses: actions/checkout@v4.1.1
        with:
          lfs: false
          submodules: true
        timeout-minutes: 3
      - name: "Debug: Check pa11y config."
        run: echo site_alias ${{ inputs.site_alias }}
        env:
          SITE_ALIAS: ${{ inputs.site_alias }}

