name: beta

on:
  workflow_call:
    inputs:
      my_site:
        type: string
        required: true
      passed_env:
        type: string
        required: true
      passed_env2:
        type: string
        required: true



jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print data passed from workflow_caller
        run: |
          echo "my_site: ${{ inputs.my_site }}"
          echo "fake passed_env: ${{ inputs.passed_env }}"
          echo "fake passed_env2: ${{ inputs.passed_env2 }}"