name: beta

on:
  workflow_call:
    inputs:
      my_site:
        type: string
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print data passed from workflow_caller
        run: |
          echo "passed data: ${{ inputs.my_site }}"