name: build-test-deploy

env:
  PR_NUMBER: ${{ github.event.number }}

on:
  pull_request_target:
    branches:
      - main

# todo preliminary-check
#      if: ${{ github.actor != github.repository_owner }} # todo trusted members instead of only owner.
# Verify that the feature branch does not change any workflow files unless author is a trusted member.
# HEAD^ is refers to the most recent commit in the repo while HEAD is the proposed new commit.
# Todo only supports owner update to check for trusted members instead.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: should not happen
        run: echo SHOULD NOT HAPPEN!

      - name: Install dependencies
        run: sudo apt-get install -y gcc

      - name: Build functions.o
        run: gcc -I. -c functions.c -o functions.o

      - name: Build main.o
        run: gcc -I. -c main.c -o main.o

      - name: Build executable
        run: gcc -I. functions.o main.o -o main_exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_exe-artifact
          path: main_exe
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: main_exe-artifact

      - name: Grant execution privilege and run test
        run: chmod 770 ./main_exe && ./main_exe

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: 'Merge pull request'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const merge_pr = await github.rest.pulls.merge({
              owner: owner,
              repo: repo,
              pull_number: ${{ env.PR_NUMBER }},
              commit_title: 'commit title placeholder',
              commit_message: 'commit message placeholder',
              merge_method: "merge"
            });
            console.log("merge_pr: ", merge_pr);