name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y gcc

      - name: Build functions.o
        run: gcc -I. -c functions.c -o functions.o

      - name: Build main.o
        run: gcc -I. -c main.c -o main.o

      - name: Build executable
        run: gcc -I. functions.o main.o -o main_exe

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Run test
        run: ./main_exe