name: build-test-deploy
on:
  pull_request

# Automatically run CICD pipeline when pull request to main is opened or edited.
# CRITICAL: Check that the feature branch of the pull request does not make any changes to main's workflows
# (preliminary check) unless changed by owner.
# Enforce checks set in author/repo -> settings -> rules -> rulesets -> status checks. If checks fail, merge is
# disabled. If pull request is from owner (or trusted members), automatically merge feature branch into main.
# Todo specify trusted members instead of only owner.


#if: ${{ github.actor == github.repository_owner }} # todo trusted members instead of only owner.
jobs:
  preliminary-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check that workflows have not been changed
      run: echo preliminary-check placeholder

  build:
    needs: preliminary-check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y gcc

      - name: Build functions.o
        run: gcc -I. -c functions.c -o functions.o

      - name: Build main.o
        run: gcc -I. -c main.c -o main.o

      - name: Build executable
        run: gcc -I. functions.o main.o -o main_exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_exe-artifact
          path: main_exe
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: main_exe-artifact

      - name: Grant execution privilege and run test
        run: chmod 770 ./main_exe && ./main_exe

  deploy:
    needs: test
    runs-on: ubuntu-latest
#    permissions: write-all
    if: ${{ github.actor == github.repository_owner }} # todo trusted members instead of only owner.
    permissions:
      contents: write # Needed to merge opened pull request
      pull-requests: write
    steps:
      - name: 'Auto approve pull request from trusted member'
        uses: actions/github-script@v6
        with:
          script: |
            console.log("github.actor:", github.actor);
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: context.ref,
              base: 'main',
              state: 'open',
            });
            const existing_pr = pulls.data[0];
            const mergePR = await github.rest.pulls.merge({
              owner: owner,
              repo: repo,
              pull_number: existing_pr.number,
              commit_title: 'commit title placeholder',
              commit_message: 'commit message placeholder',
              merge_method: "merge"
            });
#            console.log("SHOULD NOT PRINT!\n");
#            console.log('pulls.data:', pulls.data);
#            console.log('existing_pr data:', existing_pr);
#            console.log('\n\n\n mergePR:', mergePR);
