name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Say hello world!
        run: echo "$(cat hello_world.txt)"

      - name: Install dependencies
        run: sudo apt-get install -y gcc

      - name: Build
        run: gcc main.c -o main_exe

      - name: Run application
        run: ./main_exe