name: auto-pull-request

# All branches except for main.
on:
    workflow_call:
      inputs:
        PR_NUMBER:
          required: true
          type: string

# Automatically open a pull request when a trusted member pushes.
# Todo only supports owner update to check for trusted members instead.
jobs:
  beta:
    # If using a team based structure instead of a solo developer.
    # if: ${{ github.actor == github.team_slug && github.actor.permissions == approved }}

    if: ${{ github.actor == github.repository_owner }}

    runs-on: ubuntu-latest
    steps:
      - name: 'beta'
        run: echo check beta called